# GoReleaser config for guitargame
# Note: This project uses CGO (portaudio, aubio), so we only build for Linux
# Cross-compilation for macOS/Windows requires native builds on those platforms

project_name: guitargame

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: guitargame
    main: .
    binary: guitargame
    env:
      - CGO_ENABLED=1
    # Only Linux for now due to CGO dependencies
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: guitargame
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
